export global AppState {
    // Window state
    callback start-drag();
    callback close-window();
    // Authentication state
    callback initialize-app();
    in property <bool> loading: true;
    in property <bool> loggedIn: false;
    in property <bool> login-in-progress: false;
    callback login-clicked();
    // Player state
    in property <bool> is-playing: false;
    in property <string> song-title: "Albireo";
    in property <image> album-art: @image-url("../resources/album-art-placeholder.svg");
    in property <string> album: "Rokudenashi";
    in property <string> artist-name: "Rokudenashi";
    in property <string> composer: "ナユタン星人";
    in property <duration> current-time: 0s; // in seconds
    in property <duration> music-duration: 0s; // in seconds
    in property <float> volume: 1.0; // 0.0 to 1.0
    callback play();
    callback pause();
    callback volume-changed(float);
    callback seek(duration);
}
