import { AppState } from "../../state.slint";
export component AlbumArt inherits Rectangle {
    // Center the album art within available space
    album-art := Rectangle {
        width: min(root.width - 48px, root.height - 56px);
        height: self.width; // Same as width to make it square
        border-radius: 8px;
        clip: true;
        Image {
            source: AppState.album-art;
            image-fit: contain;
            width: parent.width;
            height: parent.height;
        }
    }
}
