import { ProgressBar } from "progress_bar.slint";
import { VolumeSlider } from "volume_slider.slint";
import { SongInfo } from "song_info.slint";
import { MainControls } from "main_controls.slint";
import { AdditionalControls } from "additional_controls.slint";
import { PlayerState } from "../../state.slint";

export component PlayerControls inherits Rectangle {
    vertical-stretch: 0; // Fixed size, won't shrink

    VerticalLayout {
        alignment: LayoutAlignment.stretch;
        padding: 24px;
        spacing: 16px;
        // Volume control section
        // volume-slider := VolumeSlider {
        //     volume <=> AppState.volume;
        //     volume-changed(value) => {
        //         AppState.volume-changed(value);
        //     }
        // }

        // Song information section
        song-info := SongInfo {
            song-title: PlayerState.song-title;
            artist-name: PlayerState.artist-name;
            composer: PlayerState.composer;
        }

        // Main controls section
        main-controls := MainControls {
            is-playing: PlayerState.is-playing;
            previous-clicked => {
            }
            play-pause-clicked => {
                if (PlayerState.is-playing) {
                    PlayerState.pause();
                } else {
                    PlayerState.play();
                }
            }
            next-clicked => {
            }
        }

        // Progress bar section
        progress-bar := ProgressBar {
            current-time <=> PlayerState.current-time;
            music-duration: PlayerState.music-duration;
            seek(value) => {
                PlayerState.seek(value);
                debug(value);
            }
        }

        // Additional controls section
        additional-controls := AdditionalControls {
            stop-clicked => {
            }
            shuffle-clicked => {
            }
            repeat-clicked => {
            }
            playlist-clicked => {
            }
        }
    }
}
