import { ProgressBar as CommonProgressBar } from "../common/slider.slint";
import { Utils } from "../../utils.slint";

export component ProgressBar {
    in-out property <int> current-time: 0;
    in-out property <int> music-duration: 0;
    property <float> progress: music-duration == 0 ? 0.0 : (current-time * 1.0) / music-duration;
    callback seek(int);
    // All functionality is now inherited from the common ProgressBar component
    VerticalLayout {
        padding-top: 16px;
        padding-bottom: 16px;
        CommonProgressBar {
            progress <=> root.progress;
            current-time: Utils.ms-to-string(root.current-time);
            remaining-time: Utils.ms-to-string(root.music-duration - root.current-time);
            seek(value) => {
                root.seek(value * root.music-duration);
            }
            moved(value) => {
                root.current-time = value * root.music-duration;
            }
        }
    }
}
