export component SongInfo inherits Rectangle {
    in-out property <string> song-title: "Song Title";
    in-out property <string> artist-name: "Artist Name";
    in-out property <[string]> composer: ["Composer Name 1", "Composer Name 2"];
    VerticalLayout {
        alignment: center;
        spacing: 4px;
        song-title-text := Text {
            text: root.song-title;
            color: white;
            font-size: 24px;
            font-weight: 700;
            horizontal-alignment: center;
        }

        artist-text := Text {
            text: root.artist-name;
            color: #9ca3af;
            font-size: 16px;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            spacing: 20px;
            for name in root.composer: Text {
                text: name;
                color: #6b7280;
                font-size: 14px;
                horizontal-alignment: center;
            }
        }
    }
}
